# Default values for a java8 app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: harbor.bison.sdc-prod.caas.absa.co.za/kieran-test/tue-adj-create-app_a-sample-app
  tag: latest
  pullPolicy: IfNotPresent

buildID: test

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

subatomic:
  sub-team: kieran-test
  sub-project: tue-adj-create-app
  sub-application: a-sample-app

env:
  TZ: "Africa/Johannesburg"

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "2"

livenessProbe:
  path: /actuator/info
  initialDelaySeconds: 30
  failureThreshold: 3  
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 30  
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
