# Default values for a java8 app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: harbor.bison.sdc-prod.caas.absa.co.za/thurs-andre-team/thur-andre-proj-defaults_hello-java
  tag: latest
  pullPolicy: IfNotPresent

buildID: test

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

subatomic:
  sub-team: thurs-andre-team
  sub-project: thur-andre-proj-defaults
  sub-application: hello-java

livenessProbe:
  path: /actuator/info
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  path: /actuator/health
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "1Gi"
    cpu: "2"