{{- if .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
{{ toYaml .Values.subatomic | indent 4 }}
spec:
  rules:
    {{- if .Values.ingress.fqdn }}
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - backend:
              {{- if .Values.service.name }}
              serviceName: {{ .Values.service.name }}
              {{- else }}
              serviceName: {{ template "fullname" . }}
              {{- end }}
              servicePort: {{ .Values.service.externalPort }}
    {{- end}}
    {{- if .Values.ingress.gslb }}
    - host: {{ .Values.ingress.gslb }}
      http:
        paths:
          - backend:
              {{- if .Values.service.name }}
              serviceName: {{ .Values.service.name }}
              {{- else }}
              serviceName: {{ template "fullname" . }}
              {{- end }}
              servicePort: {{ .Values.service.externalPort }}
    {{- end}}
{{- end }}